#
# Copyright (C) 2009 Niek Linnenbank, 2014 Dan Rulos (AmayaOS team)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from build import *

#
# Target system environment.
#
targetEnv = Prepare(target, [ 'libcrt', 'liballoc', 'libposix', 'libexec', 'libc' ],
		      [ 'filesystem', 'process', 'memory', 'log' ])

#
# Host system environment.
#
hostEnv   = Prepare(host, [ 'libexec' ], [ 'filesystem' ])

#
# Floppy (fd0) FileSystem server.
#
targetEnv.Program('server', [ 'floppy.c' ],
		   LIBS = targetEnv['LIBS'], LIBPATH = targetEnv['LIBPATH'])
